In [4]:
### Numerical Computing

### numpy (fast, standard, broadcasting)

### vectorization
# generate a list of the numbers from 0 to 999,999 and then multiple the list by 2

# basic (list)
raw_range = range(1000000)
raw_list = list(raw_range)
%timeit raw_list_x_2 = [x==2 for x in raw_list]


14.1 ms ± 216 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [5]:
# way 2
new_list = []
%timeit for x in raw_list: new_list.append(x*2)

19.8 ms ± 354 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [2]:
# numpy
import numpy as np
raw_arry = np.arange(1000000)
%timeit raw_arry_x_2 = 2 * raw_arry

# numpy solution is 100 times faster than list solution


592 µs ± 3.48 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [7]:
# Inner Product

def inner_product_slow(x_1: list, x_2: list) -> float:
    """
    Compute the inner product of two lists
    """

    inner_prod = 0
    for i in range(len(x_1)):
        inner_prod += x_1[i] * x_2[i]
    return inner_prod

# np.inner
x_1 = list(range(100))
x_2 = list(range(100, 200))
%timeit inner_product_slow(x_1,x_2)

np.inner(x_1,x_2) == inner_product_slow(x_1,x_2)



2.88 µs ± 44.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


True

In [8]:
# Factorial 
%timeit np.prob(np.arange(1,11))

In [ ]:
# matrix multiplication
import numpy as np
A = np.arange(10).reshape((5,2))
B = np.arange(10, 20).reshape((2,5))

print(f'Matrix A:\n {A}')
print(f'Matrix B:\n {B}')
print(f'Product:\n {A @ B}')

Matrix A:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
Matrix B:
 [[10 11 12 13 14]
 [15 16 17 18 19]]
Product:
 [[ 15  16  17  18  19]
 [ 65  70  75  80  85]
 [115 124 133 142 151]
 [165 178 191 204 217]
 [215 232 249 266 283]]


In [ ]:
# reshaping array
len_one_arr = np.ones(10)
len_one_arr.shape
# leave one dimension as -1 to tell numpy
len_two_arr = len_one_arr.reshape((-1,1))
len_two_arr.shape
# len_three_arr = len_one_arr.reshape((-1,2,1))
len_three_arr = len_one_arr.reshape((-1,2,1))
len_three_arr.shape

(10,)

In [ ]:
### Indexing in numpy
my_arr = np.arange(20).reshape((4,5))
my_arr

# access 1st row
my_arr[0,:]

#acces 1st col
my_arr[:,0]

#access first three rows and first two cols
my_arr[:3,:2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11]])

In [ ]:
### arithmetic in numpy
# multiplication
5. * my_arr
# dividing
1. / my_arr


/var/folders/gz/0z81jqhd0kj0fqg5nl86x03w0000gn/T/ipykernel_4817/2758600917.py:5: RuntimeWarning: divide by zero encountered in divide
  1. / my_arr


array([[       inf, 1.        , 0.5       , 0.33333333, 0.25      ],
       [0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111],
       [0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857],
       [0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158]])

In [ ]:
### array operaton
# multiple array by array
my_arr * my_arr

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361]])

In [ ]:
# boolean arrays with elements-wise comparisions
my_arr > 10.

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [ ]:
### boolean indexing
new_arr = np.array([4,1,0,6,6,2,6,9,6,7]).reshape((5,2))
new_arr

array([[4, 1],
       [0, 6],
       [6, 2],
       [6, 9],
       [6, 7]])

In [ ]:
# only want cols where the sum of numbers is more than 10
# first get a boolean array
cond = np.sum(new_arr, axis = 1) > 10
cond
#second, index to only such array
print(new_arr[cond])
print(new_arr[~cond])

array([False, False, False,  True,  True])

In [ ]:
### exercise: absolute value
def my_abs(arr: np.array) -> np.array:
    """Compute absolute value of an array"""

    neg_elements = arr < 0
    arr[neg_elements] = arr[neg_elements] * -1
    return arr

my_abs(np.arange(-3,3))

# alternatively, use handy np.sign function
np.arange(-3,3) * np.sign(np.arange(-3,3))

array([3, 2, 1, 0, 1, 2])

In [ ]:
### Universal Function
# vectorized math
np.exp(my_arr)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739],
       [3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894]])

In [ ]:
np.sqrt(my_arr)

In [ ]:
# aggregating functons
my_arr
np.sum(my_arr)
np.sum(my_arr, axis = 0)

array([30, 34, 38, 42, 46])

In [ ]:
# Binal Universal function
a = new_arr[:,0]
b = new_arr[:,1]
print(a,b)
np.maximum(a,b)
np.max(new_arr, axis = 1)

[4 0 6 6 6] [1 6 2 9 7]


array([4, 6, 6, 9, 7])

In [ ]:
### broadcasting
# make calculating the variance/covariance matrix of vector of random variables easy



array([[ 0.99682186, -0.05657879,  0.04291416],
       [-0.05657879,  2.00496101, -0.1085623 ],
       [ 0.04291416, -0.1085623 ,  3.09964853]])

In [ ]:
vec = np.arange(5).reshape((-1,5))
mat = np.ones(15).reshape((-1,5))
print(f'vec shape: {vec.shape}, mat shape: {mat.shape}')

# baively divede
(mat / vec).shape

# divide other direction
(vec / mat).shape

vec shape: (1, 5), mat shape: (3, 5)


/var/folders/gz/0z81jqhd0kj0fqg5nl86x03w0000gn/T/ipykernel_4817/4061457081.py:6: RuntimeWarning: divide by zero encountered in divide
  (mat / vec).shape


(3, 5)

In [ ]:
# broadcasted results
print(vec)
print(mat)
print(mat / vec)
print(vec / mat)

[[0 1 2 3 4]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[       inf 1.         0.5        0.33333333 0.25      ]
 [       inf 1.         0.5        0.33333333 0.25      ]
 [       inf 1.         0.5        0.33333333 0.25      ]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


/var/folders/gz/0z81jqhd0kj0fqg5nl86x03w0000gn/T/ipykernel_4817/3154884622.py:4: RuntimeWarning: divide by zero encountered in divide
  print(mat / vec)


In [ ]:
# Exercise: covariance matrix
import numpy as np
draws = np.random.multivariate_normal(
    mean = np.arange(6,9),
    cov = np.diag(np.arange(1,4)),
    size = 1000
)

demeaned_draws = draws - np.mean(draws, axis = 0)
demeaned_draws.T @ demeaned_draws / 1000


array([[ 1.00421434, -0.00974508,  0.01318807],
       [-0.00974508,  1.97901319,  0.02468962],
       [ 0.01318807,  0.02468962,  3.08110601]])

In [ ]:
### Exercise: Standardizing Features
# rewrite sklearn.preprocessing.StandardSccler

from sklearn.preprocessing import StandardScaler

def standardize(arr: np.array) -> np.array: 
    """
    Standardize the features in `arr`
    """

    mu_j = np.mean(arr, axis = 0)
    sigma_j = np.std(arr, axis = 0)

    return (arr - mu_j) / sigma_j

standardize(new_arr)

NameError: name 'my_arr' is not defined

In [ ]:
# random draws
draws = np.random.standard_normal(100000)
print(np.mean(draws), np.std(draws))

0.0010545200848978552 0.9973989056303378


In [ ]:
### seeds
#
rng = np.random.default_rng(seed=481) # rng = random number generator
rng_draws = rng.standard_normal(100000)
print(np.mean(rng_draws), np.std(rng_draws))


In [ ]:
### Exercise: Random
%%time
rng = np.random.default_rng(seed=481)

sample_means = []
for i in range(1000):
    sample_means.append(np.mean(rng.standard_normal(size=1000)))

print(np.mean(sample_means), np.std(sample_means))

-2.977436149096266e-05 0.031892612678989775


In [ ]:
# fast way
%%time
rng = np.random.default_rng(seed=481)

random_draws = rng.standard_normal(size=1000*1000).reshape((1000,1000))
sample_means = np.mean(random_draws, axis = 0)

print(np.mean(sample_means), np.std(sample_means))

-2.9774361490962882e-05 1.000647193189829


In [ ]:
### Application 1: Linear Regression
# (salary data) n=observations, m=variables
# first, load the data. (use panda import csv file)
# second, calculating estimator
# beta_hat = np.linalig.inv(X.T @ X) @ X.T @ y
# third, adding intersecpt

# run second with intersept
# check with sklearn or using numpy

In [5]:
# Loading data
X = np.array(
    [
        [2,1200,3.2,0],
        [1,1400,3.8,1],
        [19,900,2.5,0],
        [10,1400,3.8,1],
        [5,1000,3.0,0],
        [4,1100,3.9,0]
    ]
)
y = np.array([60000, 90000, 30000, 200000, 150000, 30000]).reshape(-1,1)

print(X.shape, y.shape)

# adding intercept
X_int = np.concatenate(
    [
        np.ones(X.shape[0]).reshape(-1,1),
        X,
    ],
    axis = 1
)
X_int

# need axis
np.concatenate(
    [
        np.ones(X.shape[0]).reshape(-1,1),
        X,
    ]
)

(6, 4) (6, 1)


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 1 and the array at index 1 has size 4

In [ ]:
# adding row/col 
# np.r, np.c
# perfomoring operation
# np.hstack
