In [1]:
### Numerical Computing

### numpy (fast, standard, broadcasting)

### vectorization
# generate a list of the numbers from 0 to 999,999 and then multiple the list by 2

# basic 
raw_range = range(1000000)
raw_list = list(raw_range)
%timeit raw_list_x_2 = [x==2 for x in raw_list]


31.1 ms ± 1.04 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
# way 2
new_list = []
for x in 

In [3]:
# numpy
import numpy as np
raw_arry = np.arange(1000000)
%timeit raw_arry_x_2 = 2 * raw_arry

# numpy solution is 100 times faster than list solution


592 µs ± 20.1 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [4]:
# np.inner
x_1_arr = np.arange(100)
x_2_arr = np.inner(1000000)

TypeError: inner() missing 1 required positional argument: 'b'

In [7]:
# matrix multiplication
import numpy as np
A = np.arange(10).reshape((5,2))
B = np.arange(10, 20).reshape((2,5))

print(f'Matrix A:\n {A}')
print(f'Matrix B:\n {B}')

Matrix A:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
Matrix B:
 [[10 11 12 13 14]
 [15 16 17 18 19]]


In [1]:
# reshaping array
# leave one dimension as -1 to tell numpy
# len_three_arr = len_one_arr.reshape((-1,2,1))

In [ ]:
### broadcasting

